### ISSUE TITLE
项目运行不起来啊

### ISSUE THREAD

**Issue by haili007** [visualization-page/vue-materials#1]
兄弟，项目运行不起来缺少模块啊。
These relative modules were not found:

* ../../../vue-ssr-template/src/components/config in ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/views/Home.vue?vue&type=script&lang=js&
* ../../../vue-ssr-template/src/views/render in ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/views/Home.vue?vue&type=script&lang=js&

**Comment by Jmingzi** [comment]
@haili007 建议查看代码思路，这个项目是用来写组件、布局等物料的。。。

**Comment by haili007** [comment]
哦 我其实是想看物料效果。
